developed team app with navbar
upaharika/TeamApp pull request #1
Opened 2022-12-01 12:05 UTC by upaharika

<img width="1769" alt="Screenshot 2022-12-01 at 12 39 15 AM" src="https://user-images.githubusercontent.com/91436152/205048528-357c212e-b2b6-4c59-8829-e064e9499f18.png">

2022-12-10 20:26 UTC, nitishnivedan commented on src/App.js
> +const CardContainer = ({ searchedTeamDetails }) => {
better to have this CardContainer in a separate file and can import here.

2022-12-10 20:27 UTC, nitishnivedan commented on src/assests/teamDetails.js
> +export const teamDetails = [
better to have a json file.

2022-12-10 20:28 UTC, nitishnivedan commented on src/components/Card/index.js
> +const CardComponent = ({ member }) => {
can de structure here further.

const CardComponent = ({ member:{ img, name, designation}})=> (
<div>

...
<div
)

2022-12-10 20:48 UTC, ap221882 reviewed
Nicely composed. Added a few suggestions.

2022-12-10 20:48 UTC, ap221882 commented on src/components/Card/index.js
> +      <img className="member-img" src={member.img}></img>
img elements must have an alt prop, either with meaningful text, or an empty string for decorative images. 
[jsx-a11y/alt-text](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/alt-text.md)

2022-12-10 20:48 UTC, ap221882 commented on src/components/SearchBar/index.js
> +  const onChange = (e) => {
name your handlers as handleChange, handleSubmit etc. React docs suggest this.

2022-12-10 20:48 UTC, ap221882 commented on src/components/SearchBar/style.css
> +input[type="text"] {
Can keep your HTML tags/ body, * selectors on top above CSS. Keeping CSS specificity in mind. I know you would have done it here unknowingly, but keep that in mind while writing vanilla CSS.

2022-12-10 20:48 UTC, ap221882 commented on src/components/SearchBar/index.js
> +      member.name.toLowerCase().includes(searchText) ||
There is a bug here. You have to make your search text also lowercase before comparing. What if someone searches for "Upaharika"? and "upaharika" doesn't match?

2022-12-10 20:48 UTC, ap221882 commented on public/index.html
> +      content="Web site created using create-react-app"
Change the description of CRA. When you deploy and share, it gives a preview using that.

2022-12-10 20:48 UTC, ap221882 commented on src/assests/teamDetails.js
> +import male from "../../src/assests/male.jpeg";
name assests as assets

2022-12-10 20:50 UTC, ap221882 reviewed
Everything good.

2022-12-11 06:36 UTC, Pujarini requested changes
Reviewed. Agree with other reviewers

2022-12-11 06:38 UTC, Pujarini requested changes

2022-12-11 06:38 UTC, Pujarini commented on src/App.js
> +  return searchedTeamDetails.map((member) => {
Too many returns when you can do it in one line.

2022-12-11 11:53 UTC, nam334 reviewed
UI looks super cool, kudos!

2022-12-11 12:25 UTC, nam334 commented on src/components/SearchBar/index.js
> +          value={searchText}
The placeholder here reads as "search restaurant"...u can change it to something relatable

2022-12-13 11:04 UTC, merged